### PR TITLE
fix(reactformvisitor): cast numbers and booleans from strings

### LINKED ISSUE #38: Bug adding element to an array of numbers
Adding a number to an array of numbers, adds a string.

**To Reproduce**
1. Go to https://concerto-ui.netlify.com
2. Click the `+` to add a new accelerometer reading
3. Edit the reading from `0` to `10`
4. Note that the JSON for the readings has added `"10"`

**Expected behavior**
Numbers should not be added as strings

**Screenshots**
Screenshot 2020-02-24 at 15 41 07

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Safari
 - Version: Latest

### PR DESCRIPTION
**Pull request by mttrbrts**
# Issue #38 
Fixes #38

### Changes
- Cast `number` and `boolean` values from `strings` in fields.

### CODE REVIEW

**Review by jeromesimeon — COMMENTED** [review]
Question: Should that logic be based on/aligned with Concerto validation. Some of those will fail once we use more strict validation in Concerto, also do we really want people to be able to write a non-valid number and have it turn into `NaN`?

**Review by jeromesimeon — CHANGES_REQUESTED** [review]
I think we should at least align with the current version of concerto. I believe that would mean:
- for Integer and Long use `parseInt`
- for Double use `parseFloat`
- for Boolean use `change === 'true'`

**Comment by mttrbrts** [comment]
I've updated the function based on the current Concerto behaviour. A more rigorous implementation will require addressing #35, I think.

**Review by jeromesimeon — APPROVED** [review]
LGTM!

**Pull request merged**
