### PR TITLE
Dark Mode for concerto-ui

### LINKED ISSUE #46: Dark Version of Concerto-UI
Bright white screen causes digital eye strain.

Describe the solution you'd like
Add a dark mode feature to concerto-ui

Why Dark Mode?
- Dark Mode prolongs battery life.
- It looks amazing.
dark

### PR DESCRIPTION
**Pull request by kanav-raina**
dark

Signed-off-by: kanav <kanavraina98@gmail.com>

# Issue #46 
Added a dark mode feature to concerto-ui

### CODE REVIEW

**Comment by Michael-Grover** [comment]
The contrast on the form is too low, is that part of this PR?

image

https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

**Comment by kanav-raina** [comment]
Yes @Michael-Grover  I have set it to grey color ,
black_design

Changed back to white color
Is this correct?

**Comment by Michael-Grover** [comment]
What do you think of making the form dark with white text when the UI is in dark mode to match the code on the left? Right now I think having the form not match the background makes it stand out too much.

**Comment by kanav-raina** [comment]
should I also change the form to the dark mode?

**Comment by Michael-Grover** [comment]
yeah I think that makes sense

**Comment by kanav-raina** [comment]
Okay @Michael-Grover.  I will also change it to dark.

**Comment by Michael-Grover** [comment]
Can we make sure the addition of dark mode doesn't affect the light mode at all?

I notice your version adds a gray box around the code in light mode, I don't think this is necessary.
image

**Comment by kanav-raina** [comment]
Okay I will not modify the light mode. I will just add changes to dark mode @Michael-Grover

**Comment by mttrbrts** [comment]
Hi @kanav-raina , thanks for your PR, this is fun! However, unfortunately, I don't really understand what value this adds to this component. 

Your changes are exclusively in the demo app (`concerto-ui-react-demo`), which although nice looking, don't help users of the `concerto-ui-react` component. There is already a rudimentary way to apply styling to the component through classes, https://github.com/accordproject/concerto-ui/blob/fe016997eb518ab5b2f03f49217d9c1e188eea67/packages/concerto-ui-react/src/concertoForm.js#L48

If you would like to contribute enhancements to the design of this component, please first open an issue where we can discuss your ideas. I wouldn't want your effort to be wasted in the future.

**Pull request closed without merging**
